name: flutter build on windows arm
on:
  push:
    branches:    
      - master
    tags: 
      - v*
jobs:
 build:
   runs-on: [self-hosted, windows, ARM64]
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'beta'
     - run: flutter config --enable-windows-desktop
     - run: flutter build windows
